# -*- coding: utf-8 -*-
"""NLP_label_for_CNN.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uYO14bgJwewBSCoCLc6dvDA2OIO9Pcnc
"""

import json

label2idx = {'opening' : 0, 'request' : 1, 'wh-question' : 2, 'yn-question' : 3,
             'inform' : 4, 'affirm' : 5, 'ack' : 6, 'expressive' : 7}

def labellist(path):
  with open(path, 'r', encoding='utf-8') as read_file:
    data = json.load(read_file)

  label_list = []
  for idx, labels in enumerate(data.values()):
    for label in labels:
      label_list.append(label2idx[label[2]])
  return len(label_list), label_list[99]

train_label_list = labellist('./SpeechAct_tr.json')
test_label_list = labellist('./SpeechAct_te.json')
print(train_label_list[0])
print(train_label_list[1])
print(test_label_list[0])
print(test_label_list[1])

save_file_name = '2019711752_윤민형_CNN_label'
with open('./'+save_file_name+'.txt', 'w', encoding='utf-8', newline='') as writer_text:
  writer_text.writelines('Train_label_list_길이 : {}'.format(train_label_list[0]) +'\n')
  writer_text.writelines('Train_Data_100번째_인덱스_label : {}'.format(train_label_list[1]) +'\n')
  writer_text.writelines('Test_label_list_길이 : {}'.format(test_label_list[0]) +'\n')
  writer_text.writelines('Test_Data_100번째_인덱스_label : {}'.format(test_label_list[1]))
  print("[저장완료]")

