# -*- coding: utf-8 -*-
"""CNN_Embedding.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UMiRp5Tbwit_CGLJz4YFxaB5VzA3_dxx
"""

!pip install PyKomoran

import json
from PyKomoran import *
import torch
import torch.nn as nn

komoran = Komoran("EXP")

with open('./SpeechAct_tr.json', 'r', encoding='utf-8') as read_file:
  data_tr = json.load(read_file)

words = []
docs = []
for key in data_tr.keys():
  text = []
  for message in data_tr[key]:
    komoran_text = komoran.get_plain_text(message[1])
    komoran_text = komoran_text.split(' ')
    text.append(komoran_text)
    for word in komoran_text:
      words.append(word)
  docs.append(text)
words_dic = sorted(set(words))

w2i = {}
w2i['<PAD>'] = 0
w2i['<UKN>'] = 1
for idx, word in enumerate(words_dic):
  w2i[word] = idx + 2

save_file_name = '2019711752_윤민형_CNN_Embed'
with open('./'+save_file_name+'.txt', 'w', encoding='utf-8', newline='') as writer_text:
  for idx, i in enumerate(docs):
    writer_text.writelines('(대화,{})'.format(idx+1) + '\n')
    for j in i:
      idx_list = []
      for k in j:
        idx_list.append(w2i[k])
      emb = nn.Embedding(num_embeddings = len(idx_list), embedding_dim = 128)
      emb_tensor = torch.tensor(emb.weight)
      emb_size = emb_tensor.size()
      writer_text.writelines(str(emb_size) + '\n')
    writer_text.writelines('\n')
  print("[저장완료]")

