# -*- coding: utf-8 -*-
"""2019711752_윤민형.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ULeBjMsW3Q0nHQB7yJKXSyH39ARCXNsv
"""

!pip install PyKomoran

import json
from PyKomoran import *
import csv

komoran = Komoran("EXP")

with open('/content/drive/My Drive/Colab Notebooks/SpeechAct.json', 'r', encoding='utf-8') as read_file:
  data = json.load(read_file)

text = []
for key in data.keys():
  for message in data[key]:
    text.append(message[1])

final_text = []
for i in range(len(text)):
  origin_text = text[i]
  komoran_text = komoran.get_plain_text(text[i])
  #print(text[i])
  #print(komoran_text, "\n")
  final_text.append(origin_text+'\n'+komoran_text+'\n\n')

save_file_name = '2019711752_윤민형'
with open('/content/drive/My Drive/Colab Notebooks/'+save_file_name+'.txt', 'w', encoding='utf-8', newline='') as writer_text:
  writer_text.writelines(final_text)

